object Libs {
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val lifeCycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifeCycleRuntimeKtx}"
    const val activityCompose = "androidx.activity:activity-compose:${Versions.activityCompose}"
    const val composeUi = "androidx.compose.ui:ui:${Versions.compose}"
    const val composeUiToolPreview = "androidx.compose.ui:ui-tooling-preview:${Versions.compose}"
    const val composeMaterial = "androidx.compose.material3:material3:${Versions.composeMaterial}"
    const val jUnit = "junit:junit:${Versions.jUnit}"
    const val composeUiManifest = "androidx.compose.ui:ui-test-manifest:${Versions.compose}"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling:${Versions.compose}"
    const val composeUiJunitTest = "androidx.compose.ui:ui-test-junit4:${Versions.compose}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val androidTestExtJunit = "androidx.test.ext:junit:${Versions.androidTestExtJunit}"
    const val androidMaterial = "com.google.android.material:material:${Versions.androidMaterial}"
    const val appCompact = "androidx.appcompat:appcompat:${Versions.appCompact}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hilt}"
    const val androidXViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.androidViewModelKtx}"
}